// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240116051834_AdmitRequestRole")]
    partial class AdmitRequestRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.DataModels.AdmitRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("address");

                    b.Property<byte>("AdmitRequestRole")
                        .HasColumnType("tinyint")
                        .HasColumnName("admit_request_role");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("avatar");

                    b.Property<byte>("BloodGroup")
                        .HasColumnType("tinyint")
                        .HasColumnName("blood_group");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("first_name");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("phone_number");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("admitRequest", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.AdmitRequestApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("AdmitRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("admit_request_id");

                    b.Property<byte>("ApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3)
                        .HasColumnName("approval_status");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("approved_by");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("comment");

                    b.Property<long?>("DeclinedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("declined_by");

                    b.HasKey("Id");

                    b.HasIndex("AdmitRequestId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("DeclinedBy");

                    b.ToTable("admitRequestApproval", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.BloodGroup", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("blood_group");

                    b.HasKey("Id");

                    b.ToTable("bloodGroup", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Title = "A+"
                        },
                        new
                        {
                            Id = (byte)2,
                            Title = "A-"
                        },
                        new
                        {
                            Id = (byte)3,
                            Title = "B+"
                        },
                        new
                        {
                            Id = (byte)4,
                            Title = "B-"
                        },
                        new
                        {
                            Id = (byte)5,
                            Title = "O+"
                        },
                        new
                        {
                            Id = (byte)6,
                            Title = "O-"
                        },
                        new
                        {
                            Id = (byte)7,
                            Title = "AB+"
                        },
                        new
                        {
                            Id = (byte)8,
                            Title = "AB-"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.Gender", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.HasKey("Id");

                    b.ToTable("gender", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Title = "Male"
                        },
                        new
                        {
                            Id = (byte)2,
                            Title = "Female"
                        },
                        new
                        {
                            Id = (byte)3,
                            Title = "Other"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("avatar");

                    b.Property<byte>("BloodGroup")
                        .HasColumnType("tinyint")
                        .HasColumnName("blood_group");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("dob");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_time");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("first_name");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<string>("Headline")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("headline");

                    b.Property<bool>("IsUserActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_user_active");

                    b.Property<bool>("IsUserDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_user_deleted");

                    b.Property<long?>("LabInstructorId")
                        .HasColumnType("bigint")
                        .HasColumnName("lab_instructor_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("last_name");

                    b.Property<string>("OTP")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("phone_number");

                    b.Property<long?>("PrincipalId")
                        .HasColumnType("bigint")
                        .HasColumnName("principal_id");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<long?>("SuspendedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("suspended_by");

                    b.Property<int?>("SuspendedDuration")
                        .HasColumnType("int")
                        .HasColumnName("suspended_duration");

                    b.Property<DateTime?>("SuspendedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("suspended_on");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("BloodGroup");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Gender");

                    b.HasIndex("LabInstructorId");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("Role");

                    b.HasIndex("SuspendedBy");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "St. Mary's School Top Floor, Besides Wockhardt Hospital",
                            Avatar = "/images/Principal-photo.jpg",
                            BloodGroup = (byte)5,
                            CreatedOn = new DateTime(2024, 1, 16, 10, 48, 34, 366, DateTimeKind.Local).AddTicks(3044),
                            DateOfBirth = new DateTime(1976, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anurag@gmail.com",
                            FirstName = "Anurag",
                            Gender = (byte)1,
                            Headline = "Principal since 2010",
                            IsUserActive = false,
                            IsUserDeleted = false,
                            LastName = "Patwardhan",
                            Password = "$2a$10$KrAm5ughTCf8bUKjZlr.SeKmffzR7tzgwMQ9fdaVxCX5uktNo19D2",
                            PhoneNumber = "8957486525",
                            Role = (byte)1,
                            UpdatedOn = new DateTime(2024, 1, 16, 5, 18, 33, 915, DateTimeKind.Utc).AddTicks(486)
                        });
                });

            modelBuilder.Entity("Entities.DataModels.UserRefreshTokens", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("userRefreshToken", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.UserRole", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("userRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Title = "Principal"
                        },
                        new
                        {
                            Id = (byte)2,
                            Title = "Teacher"
                        },
                        new
                        {
                            Id = (byte)3,
                            Title = "Student"
                        },
                        new
                        {
                            Id = (byte)4,
                            Title = "LabInstructor"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.AdmitRequest", b =>
                {
                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Entities.DataModels.AdmitRequestApproval", b =>
                {
                    b.HasOne("Entities.DataModels.AdmitRequest", "AdmitRequests")
                        .WithMany()
                        .HasForeignKey("AdmitRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DataModels.User", "DeclinedByUser")
                        .WithMany()
                        .HasForeignKey("DeclinedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdmitRequests");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("DeclinedByUser");
                });

            modelBuilder.Entity("Entities.DataModels.User", b =>
                {
                    b.HasOne("Entities.DataModels.BloodGroup", "BloodGroups")
                        .WithMany()
                        .HasForeignKey("BloodGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Entities.DataModels.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("Entities.DataModels.Gender", "Genders")
                        .WithMany()
                        .HasForeignKey("Gender")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "LabUsers")
                        .WithMany()
                        .HasForeignKey("LabInstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DataModels.User", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DataModels.UserRole", "UserRoles")
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "SuspendedByUser")
                        .WithMany()
                        .HasForeignKey("SuspendedBy");

                    b.HasOne("Entities.DataModels.User", "Teachers")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("BloodGroups");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Genders");

                    b.Navigation("LabUsers");

                    b.Navigation("Principal");

                    b.Navigation("SuspendedByUser");

                    b.Navigation("Teachers");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Entities.DataModels.UserRefreshTokens", b =>
                {
                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
